server:
  port: 9000
spring:
  main:
    web-application-type: reactive
  application:
    name: GATEWAY
  cloud:
    gateway:
      routes:
        - id: TEST
          uri: lb://TEST
          predicates:
            - Path=/test/**
eureka:
  client:
    register-with-eureka: true
    registry-fetch-interval-seconds: 1
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    initial-instance-info-replication-interval-seconds: 5
  instance:
    hostname: localhost